# Generated by Django 4.2.4 on 2023-08-30 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Search',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('GetSearch', models.CharField(default='Введите имя', max_length=100, verbose_name='Поисковой запрос')),
            ],
        ),
        migrations.CreateModel(
            name='SearchResults',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SearchResultGoogleNumber', models.CharField(max_length=10, verbose_name='Найдено результатов')),
                ('SearchResultGoogleLinks', models.TextField(max_length=2000, verbose_name='Ссылки')),
                ('date', models.DateTimeField(verbose_name='Дата запроса')),
            ],
        ),
    ]
