# Generated by Django 4.2.4 on 2023-08-31 11:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='search',
            options={'verbose_name': 'Search'},
        ),
        migrations.AlterModelOptions(
            name='searchresults',
            options={'verbose_name': 'SearchResults'},
        ),
    ]
