# Generated by Django 4.2.4 on 2023-08-31 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_search_options_alter_searchresults_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='SearchResultGoogleLinks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SearchResultGoogleLinks', models.TextField(max_length=2000, verbose_name='Ссылки')),
            ],
            options={
                'verbose_name': 'SearchResultGoogleLinks',
                'verbose_name_plural': 'SearchResultGoogleLinks',
            },
        ),
        migrations.CreateModel(
            name='SearchResultGoogleNumber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SearchResultGoogleNumber', models.CharField(max_length=10, verbose_name='Найдено результатов')),
            ],
            options={
                'verbose_name': 'SearchResultGoogleNumber',
                'verbose_name_plural': 'SearchResultGoogleNumber',
            },
        ),
        migrations.DeleteModel(
            name='SearchResults',
        ),
        migrations.AlterModelOptions(
            name='search',
            options={'verbose_name': 'Search', 'verbose_name_plural': 'Search'},
        ),
    ]
