# Generated by Django 4.2.4 on 2023-08-31 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_searchresultgooglelinks_searchresultgooglenumber_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='searchresultgooglenumber',
            name='SearchResultGoogleSearchTime',
            field=models.CharField(default='Время выполнения', max_length=4),
        ),
    ]
