# Generated by Django 4.2.4 on 2023-08-31 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_searchresultgooglenumber_searchresultgooglesearchtime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='searchresultgooglenumber',
            name='SearchResultGoogleSearchTime',
            field=models.CharField(default='Время выполнения', max_length=6),
        ),
    ]
