# Generated by Django 4.2.4 on 2023-08-31 13:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_searchresultgooglenumber_searchresultgooglesearchtime'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SearchResultGoogleLinks',
            new_name='SearchResultGoogleLink',
        ),
        migrations.RenameField(
            model_name='searchresultgooglenumber',
            old_name='SearchResultGoogleNumber',
            new_name='SearchResultGoogleNumbers',
        ),
    ]
