# Generated by Django 4.2.4 on 2023-09-01 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_alter_search_getsearch'),
    ]

    operations = [
        migrations.AlterField(
            model_name='search',
            name='SearchNumber',
            field=models.TextField(verbose_name='Номер поиска'),
        ),
    ]
